In [1]:
#import neccessary libraries
import numpy as np
import evaluation as ev
import csv
import pandas as pd
import uproot

In [2]:
#set root file name
root_file = 'Gamma-E300-n1000-part1'
root_file_name = 'step3_Gamma_E300_n1000_part1.root'

#read cluster distribution csv as a dataframe and get noise level that minimizes cluster number
df = pd.read_csv('cluster-noise-distribution_Gamma-E300-n1000-part6.csv')
noise = df['noise'][df['n_clusters_mean'].idxmin()]

#set run parameters
n_events = 1000
event_num = 19

In [3]:
#modifiedtest_single_photon function (taken from test_stats.py) that returns relevant info for each particle, as
#seen in the plot output
#(x, y, z, t, e, clusterindex, pdgid, E_bound, sum(E_hit)
#this function calls our model and tests it using the root file defined in datasets.py in the single_photon_dataset function
def particle_info(n_events, noise):
    tbeta = .2
    td = .5
    nmax = n_events
    yielder = ev.TestYielderSinglePhoton()
    yielder.model.signal_threshold = noise
    event_n = []
    event_xhit = []
    event_yhit = []
    event_zhit = []
    event_Ehit = []
    event_thit = []
    event_clusters = []
    for i, (event, prediction, clustering) in enumerate(yielder.iter_clustering(tbeta, td, nmax=nmax)):
        event_n = np.append(event_n, np.full(len(event.xhit), i))
        event_xhit = np.append(event_xhit, event.xhit)
        event_yhit = np.append(event_yhit, event.yhit)
        event_zhit = np.append(event_zhit, event.zhit)
        event_Ehit = np.append(event_Ehit, event.energy)
        event_thit = np.append(event_thit, event.time)
        event_clusters = np.append(event_clusters, clustering)
        #print(event_n)
    return event_n, event_xhit, event_yhit, event_zhit, event_Ehit, event_thit, event_clusters

#THIS IS THE SAME FUNCTION AS ABOVE BUT FOR A SINGLE EVENT


#modifiedtest_single_photon function (taken from test_stats.py) that returns relevant info for each particle, as
#seen in the plot output
#(x, y, z, t, e, clusterindex, pdgid, E_bound, sum(E_hit)
#this function calls our model and tests it using the root file defined in datasets.py in the single_photon_dataset function
def particle_info(n_events, noise):
    tbeta = .2
    td = .5
    nmax = n_events
    yielder = ev.TestYielderSinglePhoton()
    yielder.model.signal_threshold = noise
    event_n = []
    event_xhit = []
    event_yhit = []
    event_zhit = []
    event_Ehit = []
    event_thit = []
    event_clusters = []
    for i, (event, prediction, clustering) in enumerate(yielder.iter_clustering(tbeta, td, nmax=nmax)):
        print(i)
        if(i==event_num):
            event_n = np.append(event_n, np.full(len(event.xhit), i))
            event_xhit = np.append(event_xhit, event.xhit)
            event_yhit = np.append(event_yhit, event.yhit)
            event_zhit = np.append(event_zhit, event.zhit)
            event_Ehit = np.append(event_Ehit, event.energy)
            event_thit = np.append(event_thit, event.time)
            event_clusters = np.append(event_clusters, clustering)
            return event_n, event_xhit, event_yhit, event_zhit, event_Ehit, event_thit, event_clusters
        else:
            continue

In [4]:
#get 5 vectors for all events
p_5vector = particle_info(n_events, noise)

  0%|                                                                                                                                                                              | 0/1000 [00:00<?, ?it/s][uptools|    INFO|2025-03-07 11:18:06|__init__]: Using tree Events
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [11:17<00:00,  1.48it/s]

In [5]:
#write the 5vector as a pandas dataframe
df_5v = pd.DataFrame({'event_n': p_5vector[0].astype(np.int64), 'x': np.round(p_5vector[1].astype(np.float64), 2), 
                      'y': np.round(p_5vector[2].astype(np.float64), 2), 'z': np.round(p_5vector[3].astype(np.float64), 2), 
                      'e': np.round(p_5vector[4].astype(np.float64), 3), 't': p_5vector[5].astype(np.float64), 
                      'clusterindex': p_5vector[6].astype(np.int64)})

df_5v

          event_n      x      y       z      e    t  clusterindex
0               0 -41.35   3.20  322.07  0.004 -1.0             0
1               0 -33.72  -6.01  322.07  0.004 -1.0             0
2               0 -33.72   6.01  322.07  0.005 -1.0             0
3               0 -31.64   2.40  322.07  0.005 -1.0             0
4               0 -30.95  -2.00  322.07  0.004 -1.0             0
...           ...    ...    ...     ...    ...  ...           ...
18745798      999  51.97 -45.33  436.20  0.042 -1.0             0
18745799      999  15.31 -54.37  444.75  0.045 -1.0             0
18745800      999 -33.83 -57.34  453.30  0.045 -1.0             0
18745801      999 -56.82 -38.07  461.85  0.042 -1.0             0
18745802      999  25.86  43.53  478.95  0.041 -1.0             0

[18745803 rows x 7 columns]

In [6]:
#modifiedtest_single_photon function (taken from test_stats.py) that returns cluster per hit & energy per hit
#this function calls our model and tests it using the root file defined in datasets.py in the single_photon_dataset function
def clusters_info(n_events, noise):
    tbeta = .2
    td = .5
    nmax = n_events
    yielder = ev.TestYielderSinglePhoton()
    yielder.model.signal_threshold = noise
    event_n = []
    event_cluster = []
    cluster_energy = []
    cluster_nhits = []
    for i, (event, prediction, clustering) in enumerate(yielder.iter_clustering(tbeta, td, nmax=nmax)):
        #see https://stackoverflow.com/questions/67108215/how-to-get-sum-of-values-in-a-numpy-array-based-on-another-array-with-repetitive
        np.set_printoptions(suppress=True) #suppress scientific notation
        _, idx, _ = np.unique(clustering, return_counts=True, return_inverse=True)
        energy_values = np.round(np.bincount(idx, event.energy),3)
        
        event_cluster_unique, n_hits = np.unique(clustering, return_counts=True, return_index=False)
        event_i = np.full(len(event_cluster_unique), i, dtype=int)
        event_n = np.append(event_n, event_i)
        event_cluster = np.append(event_cluster, event_cluster_unique)
        cluster_nhits = np.append(cluster_nhits, n_hits)
        cluster_energy = np.append(cluster_energy, energy_values)
    return event_n, event_cluster, cluster_nhits, cluster_energy

In [7]:
#produce cluster information
ci = clusters_info(n_events, noise)

  0%|                                                                                                                                                                              | 0/1000 [00:00<?, ?it/s][uptools|    INFO|2025-03-07 11:29:25|__init__]: Using tree Events
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [08:57<00:00,  1.86it/s]

In [8]:
#create pandas dataframe with resuls from cluster mapping
df_ci = pd.DataFrame({'event_n': ci[0].astype(np.int64), 'clusterindex': ci[1].astype(np.int64), 'n_hits': ci[2].astype(np.int64), 
                      'energy_value': ci[3]})

In [9]:
#group by event and sort by n_hits
df_ci = df_ci.sort_values(['event_n', 'n_hits'],ascending=[True, False])

#add column that counts the number of clusters per event starting from zero
df_ci['cluster_count'] = df_ci.groupby(df_ci['event_n'].diff().ne(0).cumsum()).cumcount()

df_ci

      event_n  clusterindex  n_hits  energy_value  cluster_count
0           0             0   17242       140.421              0
1           0           459    1342       291.076              1
2           1             0   17665       141.895              0
3           1            10    1329       281.597              1
4           1            23       5         0.081              2
...       ...           ...     ...           ...            ...
3911      999            89       7         0.253              2
3915      999          1423       5         0.432              3
3914      999          1415       3         0.046              4
3910      999            20       1         0.015              5
3912      999           185       1         0.049              6

[3916 rows x 5 columns]

In [10]:
## save dataframe to csv
df_ci.to_csv('cluster-info_'+root_file+'_noise-'+str(noise)+'.csv', index=False)

In [11]:
#read cluster info file as dataframe
n_events = 1000
df_ci = pd.read_csv('cluster-info_'+root_file+'_noise-'+str(noise)+'.csv')

In [12]:
df_ci

      event_n  clusterindex  n_hits  energy_value  cluster_count
0           0             0   17242       140.421              0
1           0           459    1342       291.076              1
2           1             0   17665       141.895              0
3           1            10    1329       281.597              1
4           1            23       5         0.081              2
...       ...           ...     ...           ...            ...
3911      999            89       7         0.253              2
3912      999          1423       5         0.432              3
3913      999          1415       3         0.046              4
3914      999            20       1         0.015              5
3915      999           185       1         0.049              6

[3916 rows x 5 columns]

In [13]:
#open root file to load GenVtx & RecHitHGC values per event to add them as dataframe columns
events = uproot.open(root_file_name + ':Events')
root_file_name

'step3_Gamma_E300_n1000_part1.root'

In [ ]:
df_list = []
for i in range(0,n_events):
    print(i)
    df_ci_n = df_ci[df_ci['event_n']==i]
    df_5v_n = df_5v[df_5v['event_n']==i]
    #create cluster dictionary from clusterindex and cluster count to identify the signal cluster per events
    clusterN_dict = dict(zip(df_ci_n.clusterindex, df_ci_n.cluster_count))
    #create cluster energy dictionary from clusterindex and energy value to correctly assign cluster energy to 
    #each particle
    clusterE_dict = dict(zip(df_ci_n.clusterindex, df_ci_n.energy_value))
    #map each hit cluster using cluster dictionary
    df_5v_n['cluster_count'] = df_5v_n["clusterindex"].map(clusterN_dict)
    df_5v_n['sum(E_hit)'] = df_5v_n["clusterindex"].map(clusterE_dict)
    df_5v_n['RecHitHGC_x'] = np.round(events["RecHitHGC_x"].array(library="np")[i][events["RecHitHGC_z"].array(library="np")[i] > 0],2)
    df_5v_n['RecHitHGC_y'] = np.round(events["RecHitHGC_y"].array(library="np")[i][events["RecHitHGC_z"].array(library="np")[i] > 0],2)
    df_5v_n['RecHitHGC_z'] = np.round(events["RecHitHGC_z"].array(library="np")[i][events["RecHitHGC_z"].array(library="np")[i] > 0],2)
    df_5v_n['GenVtx_x'] = np.round(events["GenVtx_x"].array(library="np")[i],2)
    df_5v_n['GenVtx_y'] = np.round(events["GenVtx_y"].array(library="np")[i],2)
    df_5v_n['GenVtx_z'] = np.round(events["GenVtx_z"].array(library="np")[i],2)
    df_5v_n = df_5v_n.sort_values(['event_n', 'cluster_count'],ascending=True)
    df_list.append(df_5v_n)

df_5v_res = pd.concat(df_list)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666

In [ ]:
df_5v_res

In [ ]:
#check random event to see if clusters were mapped correctly
df_ci_n = df_ci[df_ci['event_n']==np.random.randint(0,n_events)]
df_ci_n

In [ ]:
# set cluster number to get cluster specific dataframe
cluster_n = 1

df_5v_res_n = df_5v_res[df_5v_res['cluster_count']== cluster_n]
df_5v_res_n = df_5v_res_n.reset_index(drop=True)
df_5v_res_n

In [ ]:
## save dataframe to csv
df_5v_res_n.to_csv('particle-info_'+root_file+'_noise-'+str(noise)+'_event'+str(n_events)+'_signal'+str(cluster_n)+'.csv', index=False)

In [ ]:
#read position info info file as dataframe
cluster_n = 1
df_5v_res_n = pd.read_csv('particle-info_'+root_file+'_noise-'+str(noise)+'_event'+str(n_events)+'_signal'+str(cluster_n)+'.csv')

In [ ]:
#calculate reconstructed positions wrt genvtx
df_5v_res_n['GenHit_x'] = (df_5v_res_n['GenVtx_x']/df_5v_res_n['GenVtx_z'])*(df_5v_res_n['RecHitHGC_z']-df_5v_res_n['GenVtx_z']) + df_5v_res_n['GenVtx_x']
df_5v_res_n['GenHit_y'] = (df_5v_res_n['GenVtx_y']/df_5v_res_n['GenVtx_z'])*(df_5v_res_n['RecHitHGC_z']-df_5v_res_n['GenVtx_z']) + df_5v_res_n['GenVtx_y']
df_5v_res_n['Diff_x'] = df_5v_res_n['GenHit_x'] - df_5v_res_n['RecHitHGC_x'] 
df_5v_res_n['Diff_y'] = df_5v_res_n['GenHit_y'] - df_5v_res_n['RecHitHGC_y']
df_5v_res_n

In [ ]:
## save dataframe to csv
df_5v_res_n.to_csv('particle-info_'+root_file+'_noise-'+str(noise)+'_event'+str(n_events)+'_signal'+str(cluster_n)+'.csv', index=False)